### ISSUE TITLE
Segmentation fault detected

### ISSUE THREAD

**Issue by TheCloudlet** [mzcu/minibench#2]
Thank you for your great work. 
I am testing your minibench on my project [rb_bench](https://github.com/ypaskell/rbtree_bench) and encountered some problems.

When I test your minibench on apple ARM M1 machine, the is no segmentation fault.
However, when I use linux the segmentation fault is appeared in the following line.

I cannot debug on my own since your variable `i`, `j`, `m`, `x` contains no clue of what they stand for.

![image](https://github.com/mzcu/minibench/assets/23085254/f205c10a-1b03-4f13-a634-7cc2545c4848)

**Comment by mzcu** [comment]
Hi, `ministat` code is copied (with minor adjustments to make it usable as a header-only lib) from [FreeBSD source tree](https://cgit.freebsd.org/src/tree/usr.bin/ministat/ministat.c). My guess is as good as yours here

**Comment by TheCloudlet** [comment]
Thanks
